"""
helper.py — the root-owned wrapper ('smoggle-helper') that confines Smoggle's
privileged operations on a target Mac.

Instead of granting the SSH user broad `NOPASSWD` sudo over defaults/launchctl/
pmset/etc. (effectively root), the Mac gets one root-owned script whose allowlist
is generated from the toggle registry. Sudoers grants NOPASSWD on *only* that
script, so a dashboard compromise can run nothing beyond these exact operations.

This module is the single source of truth used by BOTH the generator (the install
script served from setup.py) and the runtime router calls, so they cannot drift.
"""
from backend.executor import async_run
from backend.toggles_registry import TOGGLES

HELPER_PATH = "/usr/local/bin/smoggle-helper"
SUDOERS_PATH = "/etc/sudoers.d/smoggle"

# action name -> registry command field
_ACTION_FIELD = {"on": "cmd_on", "off": "cmd_off", "status": "cmd_status"}
_ACTIONS = ("on", "off", "status")


def _command(toggle: dict, action: str) -> str:
    return toggle[_ACTION_FIELD[action]]


def needs_helper(toggle: dict, action: str) -> bool:
    """True iff this toggle/action requires root (its registry command uses sudo).

    Per-action: e.g. power_nap on/off use sudo but status does not, and
    high_power_mode status/supported run as the user. Only sudo actions route
    through the helper; everything else runs directly as the SSH user.
    """
    return "sudo " in _command(toggle, action)


def helper_invocation(toggle_id: str, action: str) -> str:
    """The command the backend runs over SSH to invoke a privileged operation."""
    return f"sudo -n {HELPER_PATH} {toggle_id} {action}"


async def run_toggle_cmd(executor, toggle: dict, action: str):
    """Run a toggle's on/off/status command, routing privileged ones through the
    helper and running the rest directly. Returns (stdout, stderr, exit_code)."""
    if needs_helper(toggle, action):
        cmd = helper_invocation(toggle["id"], action)
    else:
        cmd = _command(toggle, action)
    return await async_run(executor, cmd)


def generate_helper_script() -> str:
    """Emit the smoggle-helper shell script: a fixed case-statement allowlist of
    exactly the registry's privileged commands, with the leading `sudo` stripped
    (the script itself runs as root). Commands are emitted as literal shell
    source so their quoting/pipes/&& survive intact."""
    lines = [
        "#!/bin/sh",
        "# Generated by Smoggle — DO NOT EDIT.",
        "# Allowlists exactly the privileged operations Smoggle performs. Installed",
        "# root-owned (0755) and granted NOPASSWD sudo via /etc/sudoers.d/smoggle.",
        'case "$1/$2" in',
    ]
    for toggle in TOGGLES:
        tid = toggle["id"]
        for action in _ACTIONS:
            if needs_helper(toggle, action):
                body = _command(toggle, action).replace("sudo ", "")
                lines.append(f"  {tid}/{action}) {body} ;;")
    lines.append('  *) echo "smoggle-helper: not permitted: $1/$2" >&2; exit 1 ;;')
    lines.append("esac")
    return "\n".join(lines) + "\n"
