"""
toggles_registry.py — Complete toggle registry as defined in SPEC.md.
Do not modify toggle definitions here; they must match the spec exactly.
"""

TOGGLES = [

  # ── HIGH IMPACT ──────────────────────────────────────────────────────

  {
    "id": "spotlight",
    "name": "Spotlight Indexing",
    "description": "File system indexing for Spotlight search",
    "purpose": "Continuously indexes files on disk to power Spotlight search and Quick Look",
    "impact": "HIGH — sporadic CPU and disk I/O bursts competing directly with unified memory bandwidth",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "sudo mdutil -a -i off",
    "cmd_on": "sudo mdutil -a -i on",
    "cmd_status": "sudo mdutil -a -s 2>/dev/null | grep -q 'Indexing enabled' && echo 1 || echo 0",
  },

  {
    "id": "timemachine",
    "name": "Time Machine Backups",
    "description": "Automatic system backups to NAS or external drive",
    "purpose": "Periodically backs up the entire system on a schedule",
    "impact": "HIGH — disk I/O and NAS bandwidth spikes at unpredictable intervals",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "sudo tmutil disable",
    "cmd_on": "sudo tmutil enable",
    "cmd_status": "val=$(sudo defaults read /Library/Preferences/com.apple.TimeMachine AutoBackup 2>/dev/null); [ \"$val\" = '1' ] && echo 1 || echo 0",
  },

  {
    "id": "photos_analysis",
    "name": "Photos ML Analysis",
    "description": "On-device face recognition, scene detection, and Memories generation",
    "purpose": "Analyzes photo library using on-device ML for People, Scenes, and Memories",
    "impact": "HIGH — directly competes with MLX/Ollama for ANE and GPU resources",
    "default_state": "on",
    "danger": 0,
    "requires_restart": True,
    "restart_note": "Photos app must be quit and relaunched for this to take effect",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "defaults write com.apple.photos PKPhotoAnalysisEnabled -bool false && defaults write com.apple.mediaanalysisd enabled -bool false",
    "cmd_on": "defaults write com.apple.photos PKPhotoAnalysisEnabled -bool true && defaults write com.apple.mediaanalysisd enabled -bool true",
    "cmd_status": "val=$(defaults read com.apple.photos PKPhotoAnalysisEnabled 2>/dev/null); [ \"$val\" = '0' ] && echo 0 || echo 1",
  },

  # ── MEDIUM IMPACT ────────────────────────────────────────────────────

  {
    "id": "icloud_sync",
    "name": "iCloud Drive Sync",
    "description": "Syncs Desktop and Documents folders to iCloud",
    "purpose": "Keeps files synchronized across Apple devices via iCloud",
    "impact": "MEDIUM — unpredictable network bursts and CPU usage",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "defaults write com.apple.bird.plist syncedDesktop -bool false 2>/dev/null; defaults write com.apple.bird.plist syncedDocuments -bool false 2>/dev/null; echo done",
    "cmd_on": "defaults write com.apple.bird.plist syncedDesktop -bool true 2>/dev/null; defaults write com.apple.bird.plist syncedDocuments -bool true 2>/dev/null; echo done",
    "cmd_status": "val=$(defaults read com.apple.bird.plist syncedDesktop 2>/dev/null); [ \"$val\" = '0' ] && echo 0 || echo 1",
  },

  {
    "id": "siri",
    "name": "Siri & Suggestions",
    "description": "Siri assistant and predictive content suggestions",
    "purpose": "Powers Siri voice queries and intelligent suggestions across macOS",
    "impact": "MEDIUM — background ML inference competing for Neural Engine access",
    "default_state": "on",
    "danger": 0,
    "requires_restart": True,
    "restart_note": "Log out and back in for Siri to fully stop background activity",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "defaults write com.apple.assistant.support 'Assistant Enabled' -bool false",
    "cmd_on": "defaults write com.apple.assistant.support 'Assistant Enabled' -bool true",
    "cmd_status": "val=$(defaults read com.apple.assistant.support 'Assistant Enabled' 2>/dev/null); [ \"$val\" = '0' ] && echo 0 || echo 1",
  },

  {
    "id": "auto_updates",
    "name": "Automatic Software Updates",
    "description": "Background update checks, downloads, and installs",
    "purpose": "Keeps macOS and App Store apps updated automatically",
    "impact": "MEDIUM — silently downloads large updates, saturates disk and network",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "sudo softwareupdate --schedule off",
    "cmd_on": "sudo softwareupdate --schedule on",
    "cmd_status": "out=$(sudo softwareupdate --schedule 2>/dev/null); echo $out | grep -q 'Automatic check is on' && echo 1 || echo 0",
  },

  {
    "id": "power_nap",
    "name": "Power Nap",
    "description": "Background tasks while display is off",
    "purpose": "Allows Mac to fetch mail, run Time Machine, and sync while display sleeps",
    "impact": "MEDIUM — wakes system unexpectedly, triggers other background daemons",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "sudo pmset -a powernap 0",
    "cmd_on": "sudo pmset -a powernap 1",
    "cmd_status": "pmset -g 2>/dev/null | grep -q 'powernap.*1' && echo 1 || echo 0",
  },

  {
    "id": "handoff",
    "name": "Handoff & Continuity",
    "description": "Bluetooth/WiFi scanning for iPhone/iPad Handoff",
    "purpose": "Enables seamless app handoff between Mac and nearby Apple devices",
    "impact": "MEDIUM — constant low-level Bluetooth and WiFi polling",
    "default_state": "on",
    "danger": 0,
    "requires_restart": True,
    "restart_note": "Toggle Bluetooth off and on for change to fully take effect",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "defaults write com.apple.coreduet.support ActivityContinuationEnabled -bool false",
    "cmd_on": "defaults write com.apple.coreduet.support ActivityContinuationEnabled -bool true",
    "cmd_status": "val=$(defaults read com.apple.coreduet.support ActivityContinuationEnabled 2>/dev/null); [ \"$val\" = '0' ] && echo 0 || echo 1",
  },

  {
    "id": "location_services",
    "name": "Location Services",
    "description": "Background location polling daemon",
    "purpose": "Provides location data to apps and system services",
    "impact": "MEDIUM — locationd polls periodically and wakes other system services",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "sudo defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd LocationServicesEnabled -bool false 2>/dev/null && sudo pkill -HUP locationd 2>/dev/null; echo done",
    "cmd_on": "sudo defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd LocationServicesEnabled -bool true 2>/dev/null && sudo pkill -HUP locationd 2>/dev/null; echo done",
    "cmd_status": "val=$(sudo defaults read /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd LocationServicesEnabled 2>/dev/null); [ \"$val\" = '0' ] && echo 0 || echo 1",
  },

  {
    "id": "mail_fetch",
    "name": "Mail Background Fetch",
    "description": "Mail.app fetches messages in the background",
    "purpose": "Keeps Mail.app inbox current when app is not in the foreground",
    "impact": "LOW-MEDIUM — periodic network activity and CPU wake events",
    "default_state": "on",
    "danger": 0,
    "requires_restart": True,
    "restart_note": "Mail.app must be quit and relaunched to stop background fetching",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "defaults write com.apple.mail.plist InboxViewerAttributes -dict-add FetchInterval -1",
    "cmd_on": "defaults write com.apple.mail.plist InboxViewerAttributes -dict-add FetchInterval 5",
    "cmd_status": "val=$(defaults read com.apple.mail InboxViewerAttributes 2>/dev/null | grep -o 'FetchInterval = [^;]*' | awk '{print $3}'); [ \"$val\" = '-1' ] && echo 0 || echo 1",
  },

  {
    "id": "analytics",
    "name": "Apple Analytics & Diagnostics",
    "description": "Sends usage and diagnostic data to Apple on a schedule",
    "purpose": "Collects crash reports and usage analytics for Apple",
    "impact": "LOW-MEDIUM — scheduled background process competing for disk and network",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["performance", "max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "defaults write com.apple.SubmitDiagInfo AutoSubmit -bool false; defaults write com.apple.assistant.support 'Siri Data Sharing Opt-In Status' -int 2; echo done",
    "cmd_on": "defaults write com.apple.SubmitDiagInfo AutoSubmit -bool true; echo done",
    "cmd_status": "val=$(defaults read com.apple.SubmitDiagInfo AutoSubmit 2>/dev/null); [ \"$val\" = '0' ] && echo 0 || echo 1",
  },

  {
    "id": "airplay_receiver",
    "name": "AirPlay Receiver",
    "description": "Allows this Mac to receive AirPlay streams from other devices",
    "purpose": "Runs a persistent daemon so other devices can stream to this Mac",
    "impact": "LOW-MEDIUM — persistent daemon with open network socket and keepalive traffic",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "launchctl unload -w /System/Library/LaunchAgents/com.apple.AirPlayUIAgent.plist 2>/dev/null; defaults write com.apple.airplay AirPlayReceiverEnabled -bool false; echo done",
    "cmd_on": "launchctl load -w /System/Library/LaunchAgents/com.apple.AirPlayUIAgent.plist 2>/dev/null; defaults write com.apple.airplay AirPlayReceiverEnabled -bool true; echo done",
    "cmd_status": "val=$(defaults read com.apple.airplay AirPlayReceiverEnabled 2>/dev/null); [ \"$val\" = '0' ] && echo 0 || echo 1",
  },

  # ── CAUTION ───────────────────────────────────────────────────────────

  {
    "id": "ollama",
    "name": "Ollama Service",
    "description": "Ollama LLM inference server (launchd managed)",
    "purpose": "Runs the Ollama inference server as a persistent background service",
    "impact": "CRITICAL if running alongside MLX — both compete for unified memory",
    "default_state": "on",
    "danger": 1,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "plist=$(find ~/Library/LaunchAgents /Library/LaunchAgents -name '*ollama*' 2>/dev/null | head -1); if [ -n \"$plist\" ]; then launchctl unload -w \"$plist\" && echo done; else pkill -x ollama 2>/dev/null; echo done; fi",
    "cmd_on": "plist=$(find ~/Library/LaunchAgents /Library/LaunchAgents -name '*ollama*' 2>/dev/null | head -1); if [ -n \"$plist\" ]; then launchctl load -w \"$plist\" && echo done; else echo no_plist; fi",
    "cmd_status": "pgrep -x ollama > /dev/null 2>&1 && echo 1 || echo 0",
  },

  {
    "id": "app_nap",
    "name": "App Nap",
    "description": "macOS throttles background apps it considers inactive",
    "purpose": "Reduces CPU and power for apps not currently visible",
    "impact": "MEDIUM — can throttle inference server processes; disabling ensures full CPU for background workloads",
    "default_state": "on",
    "danger": 1,
    "requires_restart": True,
    "restart_note": "Ollama and MLX server must be restarted to reflect new App Nap state",
    "profiles": ["max", "hyper"],
    "apple_silicon_only": True,
    "cmd_off": "defaults write NSGlobalDomain NSAppSleepDisabled -bool YES",
    "cmd_on": "defaults write NSGlobalDomain NSAppSleepDisabled -bool NO",
    "cmd_status": "val=$(defaults read NSGlobalDomain NSAppSleepDisabled 2>/dev/null); [ \"$val\" = '1' ] && echo 0 || echo 1",
  },

  {
    "id": "high_power_mode",
    "name": "High Power Mode",
    "description": "Locks Mac to sustained maximum performance",
    "purpose": "Disables energy-saving governor, prevents thermal throttling",
    "impact": "POSITIVE — prevents performance drops mid-inference; increases power draw and fan activity",
    "default_state": "off",
    "danger": 1,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["max", "hyper"],
    "apple_silicon_only": True,
    "cmd_supported": "pmset -g 2>/dev/null | grep -q highpowermode && echo 1 || echo 0",
    "cmd_off": "sudo pmset -a highpowermode 0",
    "cmd_on": "sudo pmset -a highpowermode 1",
    "cmd_status": "pmset -g 2>/dev/null | grep -q 'highpowermode.*1' && echo 1 || echo 0",
  },

  # ── DANGER ────────────────────────────────────────────────────────────

  {
    "id": "notification_center",
    "name": "Notification Center",
    "description": "System-wide notification delivery daemon",
    "purpose": "Delivers all app and system notifications to the user",
    "impact": "LOW — minor CPU wakeups; included in Hyper for completeness",
    "default_state": "on",
    "danger": 0,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["hyper"],
    "apple_silicon_only": True,
    "cmd_off": "defaults write com.apple.notificationcenterui doNotDisturb -bool true; defaults write com.apple.ncprefs dnd_prefs -dict-add userPref -int 1; echo done",
    "cmd_on": "defaults write com.apple.notificationcenterui doNotDisturb -bool false; defaults write com.apple.ncprefs dnd_prefs -dict-add userPref -int 0; echo done",
    "cmd_status": "val=$(defaults read com.apple.notificationcenterui doNotDisturb 2>/dev/null); [ \"$val\" = '1' ] && echo 0 || echo 1",
  },

  {
    "id": "mdns",
    "name": "mDNS / Bonjour",
    "description": "Local network discovery protocol",
    "purpose": "Enables AirDrop, AirPlay, Handoff, HomeKit, and local network discovery",
    "impact": "LOW — minor network overhead; breaks AirDrop, AirPlay, some HomeKit when disabled",
    "default_state": "on",
    "danger": 2,
    "requires_restart": False,
    "restart_note": "",
    "profiles": ["hyper"],
    "apple_silicon_only": True,
    "cmd_off": "sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool true && sudo pkill -HUP mDNSResponder 2>/dev/null; echo done",
    "cmd_on": "sudo defaults delete /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements 2>/dev/null; sudo pkill -HUP mDNSResponder 2>/dev/null; echo done",
    "cmd_status": "val=$(sudo defaults read /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements 2>/dev/null); [ \"$val\" = '1' ] && echo 0 || echo 1",
  },

]

TOGGLES_BY_ID = {t["id"]: t for t in TOGGLES}
