"""
test_ssh_identity.py — tests for SSH key generation and management.

Uses the session-scoped temp key path from conftest. Since the key is generated
once per session (by the first client fixture), these tests verify it exists
and is well-formed rather than testing generation in isolation.
"""
import os

import backend.ssh_identity as ssh_identity


def test_keypair_exists():
    """The keypair should have been generated by the first client fixture."""
    ssh_identity.ensure_identity()
    assert os.path.exists(ssh_identity.KEY_PATH)
    assert os.path.exists(ssh_identity.PUB_PATH)


def test_ensure_identity_idempotent():
    """Calling ensure_identity again should not change the key."""
    pub1 = ssh_identity.get_public_key()
    ssh_identity.ensure_identity()
    pub2 = ssh_identity.get_public_key()
    assert pub1 == pub2


def test_private_key_permissions():
    """Private key must be 0600."""
    mode = oct(os.stat(ssh_identity.KEY_PATH).st_mode & 0o777)
    assert mode == "0o600"


def test_public_key_format():
    """Public key should be an Ed25519 key with the smoggle comment."""
    pub = ssh_identity.get_public_key()
    assert pub.startswith("ssh-ed25519 ")
    assert pub.endswith(" smoggle")
